name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            cd github-actions-demo || git clone https://github.com/Harsha124-work/github-actions-demo.git 
            cd github-actions-demo
            git pull origin main
            npm install
            pm2 restart app || pm2 start app.js
